### ISSUE TITLE
Cannot create a new instance of Bundlr

### ISSUE THREAD

**Issue by mzmarshall1278** [Bundlr-Network/js-sdk#50]
I get TypeError: Bundlr is not a constructor when I call new on Bundlr from my imports. 
I am using version "^0.7.16".

**Comment by joshbenaron** [comment]
Hey! Thanks for reporting this issue. When you're using vanilla JS you need to do `Bundlr.default`

e.g.

```js
const Bundlr = require("@bundlr-network/client");
// OR
import Bundlr from "@bundlr-network/client";

const bundlr = new Bundlr.default(...);
```
